source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    nil
encoding:    nil

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

forums_url: http://54.244.249.23/forum/
api_docs_url: http://bridgeit.github.io/bridgeit.js/docs/html/
icesoft_url: http://www.icesoft.org
os_license_url: http://www.apache.org/licenses/LICENSE-2.0/
privacy_url: http://www.icesoft.org/java/about/privacy-policy.jsf
twitter_url: https://twitter.com/BridgeItApp
facebook_url: https://www.facebook.com/
github_url: http://github.io/bridgeit/
demo_url: http://bridgeit.github.io/demo/
jqmdemo_url: http://bridgeit.github.io/demo-jqm/
bridgeit_js_url: http://bridgeit.github.io/bridgeit/src/bridgeit.js
github_js_url: http://bridgeit.github.io/bridgeit/src/bridgeit.js
version_js_url: http://bridgeit.github.io/bridgeit/src/bridgeit.js
apple_app_url: http://itunes.apple.com/us/app/icemobile-sx/id485908934?mt=8
android_app_url: https://play.google.com/store/apps/details?id=mobi.bridgeit
windows_app_url: http://www.windowsphone.com/store/